from typing import Tuple

import numpy as np
from ase import Atoms
from phonopy import Phonopy
from phonopy.structure.atoms import PhonopyAtoms


def structure_calculate_phonons(
    atoms: Atoms,
    displacement: float,
    supercell: Tuple[int, int, int],
    qpoint_mesh: Tuple[int, int, int],
    progress_callback=None,
    calculator_for=None,
) -> Phonopy:
    if atoms.calc is None:
        raise RuntimeError("No calculator set for the structure.")

    phnpy_structure = PhonopyAtoms(
        symbols=atoms.get_chemical_symbols(),
        positions=atoms.get_positions(),
        cell=atoms.get_cell().array,
    )

    phonons = Phonopy(
        phnpy_structure,
        supercell_matrix=np.diag(supercell),
        primitive_matrix="auto",
    )

    phonons.generate_displacements(distance=displacement)

    sets_of_forces = []
    supercells = phonons.supercells_with_displacements

    if supercells is None:
        raise RuntimeError("Distorted cells were not generated by Phonopy.")

    from rapmat.calculators import cleanup_calculator_files

    cleanup_calculator_files(atoms.calc)

    counter = 0
    for phonopy_cell in supercells:
        counter += 1
        if progress_callback:
            progress_callback(
                0, 0, f"Processing deformed structure {counter}/{len(supercells)}"
            )

        cleanup_calculator_files(atoms.calc)

        ase_cell = Atoms(
            symbols=phonopy_cell.symbols,
            positions=phonopy_cell.positions,
            cell=phonopy_cell.cell,
            pbc=True,
        )

        ase_cell.calc = (
            atoms.calc if calculator_for is None else calculator_for(ase_cell)
        )

        forces = ase_cell.get_forces()
        sets_of_forces.append(forces)

    phonons.forces = np.array(sets_of_forces)
    phonons.produce_force_constants()
    phonons.symmetrize_force_constants()
    phonons.run_mesh(qpoint_mesh)

    return phonons


def calculate_phonons_with_freq(
    atoms: Atoms,
    *,
    calculator_for,
    displacement: float,
    supercell: Tuple[int, int, int],
    qpoint_mesh: Tuple[int, int, int],
    reduce_primitive: bool = True,
    symprec: float = 1e-3,
    progress_callback=None,
    log_label: str | None = None,
    log_callback=None,
) -> Tuple[Phonopy, float]:
    """Run a phonon calculation and return both the ``Phonopy`` object and the
    minimum frequency."""
    if reduce_primitive:
        from rapmat.utils.structure import standardize_atoms

        n_before = len(atoms)
        atoms = standardize_atoms(atoms, to_primitive=True, symprec=symprec)
        if log_callback and log_label:
            log_callback(f"Reducing {log_label}: {n_before} -> {len(atoms)} atoms")

    atoms.calc = calculator_for(atoms)
    phonons = structure_calculate_phonons(
        atoms,
        displacement=displacement,
        supercell=supercell,
        qpoint_mesh=qpoint_mesh,
        progress_callback=progress_callback,
        calculator_for=calculator_for,
    )
    return phonons, get_mesh_min_frequency(phonons)


def calculate_min_phonon_freq(
    atoms: Atoms,
    *,
    calculator_for,
    displacement: float,
    supercell: Tuple[int, int, int],
    qpoint_mesh: Tuple[int, int, int],
    reduce_primitive: bool = True,
    symprec: float = 1e-3,
    progress_callback=None,
    log_label: str | None = None,
    log_callback=None,
) -> float:
    _phonons, min_freq = calculate_phonons_with_freq(
        atoms,
        calculator_for=calculator_for,
        displacement=displacement,
        supercell=supercell,
        qpoint_mesh=qpoint_mesh,
        reduce_primitive=reduce_primitive,
        symprec=symprec,
        progress_callback=progress_callback,
        log_label=log_label,
        log_callback=log_callback,
    )
    return min_freq


def get_mesh_min_frequency(phonons: Phonopy) -> float:
    return float(np.min(phonons.get_mesh_dict()["frequencies"]))


def structure_has_imag_phonon_freq(phonons: Phonopy, threshold: float = -1e-3) -> bool:
    return get_mesh_min_frequency(phonons) < threshold


# ------------------------------------------------------------------ #
#  Persistence
# ------------------------------------------------------------------ #


def serialize_phonons(phonons: Phonopy) -> str:
    """Serialize a Phonopy object to a gzip -> base64.
    """
    import base64
    import gzip

    from phonopy.interface.phonopy_yaml import PhonopyYaml

    py = PhonopyYaml(settings={"force_constants": False})
    py.set_phonon_info(phonons)
    raw = str(py).encode("utf-8")
    return base64.b64encode(gzip.compress(raw)).decode("ascii")


def deserialize_phonons(blob: str) -> Phonopy:
    """Reconstruct a Phonopy object from a string.
    """
    import base64
    import gzip
    import os
    import tempfile

    import phonopy

    text = gzip.decompress(base64.b64decode(blob)).decode("utf-8")
    tmp = tempfile.NamedTemporaryFile(
        "w", suffix=".phonopy.yaml", delete=False, encoding="utf-8"
    )
    try:
        tmp.write(text)
        tmp.close()

        return phonopy.load(tmp.name, produce_fc=True)
    finally:
        os.unlink(tmp.name)


def save_phonon_dispersion(phonons: Phonopy, save_path) -> None:
    """Render and save a phonon dispersion plot."""
    import warnings

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fig = phonons.auto_band_structure(plot=True)
    fig.savefig(str(save_path), dpi=150)
    plt.close(fig)
